### ISSUE TITLE
Crash when loaded alongside FabricAPI?

### ISSUE THREAD

**Issue by Derpford** [CorgiTaco-Archive/Upstream#1] opened 2020-12-17 05:04 UTC
When I load Upstream by itself, it loads fine. However, when I have FabricAPI loaded alongside it, *this* happens:

https://pastebin.com/aM11vLHC

A crash, specifically `net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'fabric-networking-api-v1'`. Did you package an older FabricAPI with your mod or something?

**Comment by CorgiTaco** [comment] 2020-12-17 05:05
uhhhhhhhhhhhh i dont even package fabric api

**Comment by CorgiTaco** [comment] 2020-12-17 05:13
Video proof of the target existing: https://imgur.com/a/w6WSg2h

**Comment by Derpford** [comment] 2020-12-17 05:16
If you're not packaging FabricAPI, how is it that your mod doesn't crash when loaded alone, but *does* crash when FabricAPI is loaded? I'm not sure how loading FabricAPI would suddenly make something else disappear.

**Comment by CorgiTaco** [comment] 2020-12-17 05:18
Idk man: https://github.com/CorgiTaco/Upstream/blob/Fabric-1.16.X/src/main/java/corgitaco/upstream/mixin/MixinMinecraftServer.java#L38

Like it's literally off in my build.gradle: <https://github.com/CorgiTaco/Upstream/blob/Fabric-1.16.X/build.gradle#L20>

**Comment by CorgiTaco** [comment] 2020-12-17 05:19
And your actual crash is this: `Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on addBYGFeatures could not find any targets matching '<init>(Ljava/lang/Thread;Lnet/minecraft/util/registry/DynamicRegistryManager$Impl;Lnet/minecraft/world/level/storage/LevelStorage$Session;Lnet/minecraft/world/SaveProperties;Lnet/minecraft/resource/ResourcePackManager;Ljava/net/Proxy;Lcom/mojang/datafixers/DataFixer;Lnet/minecraft/resource/ServerResourceManager;Lcom/mojang/authlib/minecraft/MinecraftSessionService;Lcom/mojang/authlib/GameProfileRepository;Lnet/minecraft/util/UserCache;Lnet/minecraft/server/WorldGenerationProgressListenerFactory;)V' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> upstream.mixins.json:MixinMinecraftServer -> Prepare Injections ->  -> handler$zfb000$addBYGFeatures(Ljava/lang/Thread;Lnet/minecraft/class_5455$class_5457;Lnet/minecraft/class_32$class_5143;Lnet/minecraft/class_5219;Lnet/minecraft/class_3283;Ljava/net/Proxy;Lcom/mojang/datafixers/DataFixer;Lnet/minecraft/class_5350;Lcom/mojang/authlib/minecraft/MinecraftSessionService;Lcom/mojang/authlib/GameProfileRepository;Lnet/minecraft/class_3312;Lnet/minecraft/class_3950;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]`

**Comment by Derpford** [comment] 2020-12-17 05:20
Okay, but why does this trigger on adding Fabric API?

**Comment by CorgiTaco** [comment] 2020-12-17 05:20
Im as lost as you are boss

**Comment by CorgiTaco** [comment] 2020-12-17 05:32
![image](https://user-images.githubusercontent.com/66983020/102448089-3b9b6600-3fe6-11eb-9b51-04b4171938d9.png)

**Comment by CorgiTaco** [comment] 2020-12-17 05:41
Works in dev, breaks in game

**Comment by CorgiTaco** [comment] 2020-12-17 20:40
Fixed in latest upstream fabric build!

**Closed as completed** 2020-12-17 20:40 UTC
